package cameo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CAMEO_CODES {

    private static final Map<String, String> codeAsKey;
    private static final Map<String, String> valueAsKey;

    /**
     * Takes the code id and returns the value of the code
     */
    public static String getTileFromId(String id) {
       return codeAsKey.get(id);
    }

    /**
     * Takes a value as parameter and returns all codes containing that value
     */
    public static List<String> getCode(String value) {
        List<String> allCodes = new ArrayList<>();
        for (String s : valueAsKey.keySet()) {
            if (s.contains(value.toLowerCase())) {
                allCodes.add(valueAsKey.get(s));
            }
        }

        return allCodes;
    }

    static
    {
        codeAsKey= new HashMap<String, String>();
        codeAsKey.put("01", "MAKE PUBLIC STATEMENT");
        codeAsKey.put("010", "Make statement");
        codeAsKey.put("012", "Make pessimistic comment");
        codeAsKey.put("013", "Make optimistic comment");
        codeAsKey.put("014", "Consider policy option");
        codeAsKey.put("015", "Acknowledge or claim responsibility 016");
        codeAsKey.put("017", "Engage in symbolic act");
        codeAsKey.put("018", "Make empathetic comment");
        codeAsKey.put("019", "Express accord");
        codeAsKey.put("02", "APPEAL");
        codeAsKey.put("020", "Make an appeal or request");
        codeAsKey.put("021", "Appeal for material cooperation");
        codeAsKey.put("0211", "Appeal for economic cooperation 0212");
        codeAsKey.put("022", "Appeal for diplomatic cooperation (such as policy support) 023");
        codeAsKey.put("0231", "Appeal for economic aid");
        codeAsKey.put("0232", "Appeal for military aid");
        codeAsKey.put("0233", "Appeal for humanitarian aid");
        codeAsKey.put("0234", "Appeal for military protection or peacekeeping");
        codeAsKey.put("024", "Appeal for political reform");
        codeAsKey.put("0242", "Appeal for policy change");
        codeAsKey.put("0243", "Appeal for rights");
        codeAsKey.put("0244", "Appeal for change in institutions");
        codeAsKey.put("0251", "Appeal for easing of administrative sanctions 0252");
        codeAsKey.put("0253", "Appeal for release of persons or property");
        codeAsKey.put("0254", "Appeal for easing of economic sanctions");
        codeAsKey.put("0255", "Appeal for target to allow international involvement (non-mediation) 0256");
        codeAsKey.put("026", "Appeal to others to meet or negotiate 027");
        codeAsKey.put("028", "Appeal to engage in or accept mediation");
        codeAsKey.put("03", "EXPRESS INTENT TO COOPERATE");
        codeAsKey.put("030", "Express intent to cooperate");
        codeAsKey.put("031", "Express intent to engage in material cooperation");
        codeAsKey.put("0311", "Express intent to cooperate economically");
        codeAsKey.put("0312", "Express intent to cooperate militarily");
        codeAsKey.put("0313", "Express intent to cooperate on judicial matters 0314");
        codeAsKey.put("032", "Express intent to engage in diplomatic cooperation (such as policy support) 033");
        codeAsKey.put("0331", "Express intent to provide economic aid");
        codeAsKey.put("0332", "Express intent to provide military aid");
        codeAsKey.put("0333", "Express intent to provide humanitarian aid");
        codeAsKey.put("0334", "Express intent to provide military protection or peacekeeping");
        codeAsKey.put("034", "Express intent to institute political reform");
        codeAsKey.put("0342", "Express intent to change policy");
        codeAsKey.put("0343", "Express intent to provide rights");
        codeAsKey.put("0344", "Express intent to change institutions");
        codeAsKey.put("0351", "Express intent to ease administrative sanctions");
        codeAsKey.put("0352", "Express intent to ease popular dissent");
        codeAsKey.put("0353", "Express intent to release persons or property");
        codeAsKey.put("0354", "Express intent to ease economic sanctions");
        codeAsKey.put("036", "Express intent to meet or negotiate 037");
        codeAsKey.put("04", "CONSULT");
        codeAsKey.put("040", "Consult");
        codeAsKey.put("042", "Make a visit");
        codeAsKey.put("043", "Host a visit");
        codeAsKey.put("044", "Meet at a ”third” location 045");
        codeAsKey.put("046", "Engage in negotiation");
        codeAsKey.put("05", "ENGAGE IN DIPLOMATIC COOPERATION");
        codeAsKey.put("050", "Engage in diplomatic cooperation");
        codeAsKey.put("052", "Defend verbally");
        codeAsKey.put("053", "Rally support on behalf of");
        codeAsKey.put("054", "Grant diplomatic recognition 055");
        codeAsKey.put("056", "Forgive");
        codeAsKey.put("057", "Sign formal agreement");
        codeAsKey.put("06", "ENGAGE IN MATERIAL COOPERATION");
        codeAsKey.put("060", "Engage in material cooperation");
        codeAsKey.put("062", "Cooperate militarily");
        codeAsKey.put("063", "Engage in judicial cooperation");
        codeAsKey.put("064", "Share intelligence or information");
        codeAsKey.put("07", "PROVIDE AID");
        codeAsKey.put("070", "Provide aid");
        codeAsKey.put("072", "Provide military aid");
        codeAsKey.put("073", "Provide humanitarian aid");
        codeAsKey.put("074", "Provide military protection or peacekeeping 075");
        codeAsKey.put("08", "YIELD");
        codeAsKey.put("080", "Yield");
        codeAsKey.put("081", "Ease administrative sanctions");
        codeAsKey.put("0811", "Ease restrictions on political freedoms 0812");
        codeAsKey.put("0814", "Ease state of emergency or martial law");
        codeAsKey.put("082", "Ease political dissent");
        codeAsKey.put("083", "Accede to requests or demands for political reform");
        codeAsKey.put("0831", "Accede to demands for change in leadership");
        codeAsKey.put("0832", "Accede to demands for change in policy");
        codeAsKey.put("0833", "Accede to demands for rights");
        codeAsKey.put("0834", "Accede to demands for change in institutions");
        codeAsKey.put("084", "Return");
        codeAsKey.put("085", "Ease economic sanctions");
        codeAsKey.put("086", "Allow international involvement");
        codeAsKey.put("0861", "Receive deployment of peacekeepers 0862");
        codeAsKey.put("0863", "Allow humanitarian access");
        codeAsKey.put("087", "De-escalate military engagement 0871");
        codeAsKey.put("0872", "Ease military blockade");
        codeAsKey.put("0873", "Demobilize armed forces");
        codeAsKey.put("0874", "Retreat or surrender militarily");
        codeAsKey.put("09", "INVESTIGATE");
        codeAsKey.put("090", "Investigate");
        codeAsKey.put("094", "Investigate war crimes");
        codeAsKey.put("10", "DEMAND");
        codeAsKey.put("100", "Demand");
        codeAsKey.put("101", "Demand material cooperation");
        codeAsKey.put("1011", "Demand economic cooperation 1012");
        codeAsKey.put("102", "Demand diplomatic cooperation (such as policy support) 103");
        codeAsKey.put("1031", "Demand economic aid");
        codeAsKey.put("1032", "Demand military aid");
        codeAsKey.put("1033", "Demand humanitarian aid");
        codeAsKey.put("1034", "Demand military protection or peacekeeping");
        codeAsKey.put("104", "Demand political reform");
        codeAsKey.put("1042", "Demand policy change");
        codeAsKey.put("1043", "Demand rights");
        codeAsKey.put("1044", "Demand change in institutions");
        codeAsKey.put("1051", "Demand easing of administrative sanctions");
        codeAsKey.put("1052", "Demand easing of political dissent");
        codeAsKey.put("1053", "Demand release of persons or property");
        codeAsKey.put("1054", "Demand easing of economic sanctions");
        codeAsKey.put("1055", "Demand that target allows international involvement (non-mediation) 1056");
        codeAsKey.put("106", "Demand meeting");
        codeAsKey.put("11", "DISAPPROVE");
        codeAsKey.put("110", "Disapprove");
        codeAsKey.put("112", "Accuse");
        codeAsKey.put("1121", "Accuse of crime");
        codeAsKey.put("1124", "Accuse of war crimes");
        codeAsKey.put("1125", "Accuse of espionage");
        codeAsKey.put("113", "Rally opposition against 114");
        codeAsKey.put("115", "Bring lawsuit against");
        codeAsKey.put("116", "Find guilty or liable (legally)");
        codeAsKey.put("12", "REJECT");
        codeAsKey.put("120", "Reject");
        codeAsKey.put("1211", "Reject economic cooperation");
        codeAsKey.put("1212", "Reject military cooperation");
        codeAsKey.put("122", "Reject request or demand for material aid");
        codeAsKey.put("1221", "Reject request for economic aid");
        codeAsKey.put("1222", "Reject request for military aid");
        codeAsKey.put("1223", "Reject request for humanitarian aid");
        codeAsKey.put("1224", "Reject request for military protection or peacekeeping");
        codeAsKey.put("123", "Reject request or demand for political reform");
        codeAsKey.put("1232", "Reject request for policy change");
        codeAsKey.put("1233", "Reject request for rights");
        codeAsKey.put("1234", "Reject request for change in institutions");
        codeAsKey.put("1241", "Refuse to ease administrative sanctions");
        codeAsKey.put("1242", "Refuse to ease popular dissent");
        codeAsKey.put("1243", "Refuse to release persons or property");
        codeAsKey.put("1244", "Refuse to ease economic sanctions");
        codeAsKey.put("125", "Reject proposal to meet");
        codeAsKey.put("127", "Reject plan");
        codeAsKey.put("128", "Defy norms");
        codeAsKey.put("129", "Veto");
        codeAsKey.put("13", "THREATEN");
        codeAsKey.put("130", "Threaten");
        codeAsKey.put("131", "Threaten non-force");
        codeAsKey.put("1311", "Threaten to reduce or stop aid");
        codeAsKey.put("1312", "Threaten with sanctions");
        codeAsKey.put("1313", "Threaten to reduce or break relations");
        codeAsKey.put("132", "Threaten with administrative sanctions");
        codeAsKey.put("1321", "Threaten with restrictions on political freedoms");
        codeAsKey.put("1322", "Threaten to ban political parties or politicians");
        codeAsKey.put("1323", "Threaten to impose curfew");
        codeAsKey.put("1324", "Threaten to impose state of emergency or martial law");
        codeAsKey.put("133", "Threaten with political dissent");
        codeAsKey.put("134", "Threaten to halt negotiations");
        codeAsKey.put("135", "Threaten to halt mediation");
        codeAsKey.put("136", "Threaten to halt international involvement (non-mediation) 137");
        codeAsKey.put("138", "Threaten with military force");
        codeAsKey.put("1382", "Threaten occupation");
        codeAsKey.put("1383", "Threaten unconventional violence");
        codeAsKey.put("1384", "Threaten conventional attack");
        codeAsKey.put("1385", "Threaten attack with WMD 139");
        codeAsKey.put("14", "PROTEST");
        codeAsKey.put("140", "Engage in political dissent");
        codeAsKey.put("1411", "Demonstrate for leadership change");
        codeAsKey.put("1412", "Demonstrate for policy change");
        codeAsKey.put("1413", "Demonstrate for rights");
        codeAsKey.put("1414", "Demonstrate for change in institutions");
        codeAsKey.put("142", "Conduct hunger strike");
        codeAsKey.put("1421", "Conduct hunger strike for leadership change");
        codeAsKey.put("1422", "Conduct hunger strike for policy change");
        codeAsKey.put("1423", "Conduct hunger strike for rights");
        codeAsKey.put("1424", "Conduct hunger strike for change in institutions");
        codeAsKey.put("143", "Conduct strike or boycott");
        codeAsKey.put("1431", "Conduct strike or boycott for leadership change");
        codeAsKey.put("1432", "Conduct strike or boycott for policy change");
        codeAsKey.put("1433", "Conduct strike or boycott for rights");
        codeAsKey.put("1434", "Conduct strike or boycott for change in institutions");
        codeAsKey.put("144", "Obstruct passage");
        codeAsKey.put("1441", "Obstruct passage to demand leadership change");
        codeAsKey.put("1442", "Obstruct passage to demand policy change");
        codeAsKey.put("1443", "Obstruct passage to demand rights");
        codeAsKey.put("1444", "Obstruct passage to demand change in institutions");
        codeAsKey.put("145", "Protest violently");
        codeAsKey.put("1451", "Engage in violent protest for leadership change");
        codeAsKey.put("1452", "Engage in violent protest for policy change");
        codeAsKey.put("1453", "Engage in violent protest for rights");
        codeAsKey.put("1454", "Engage in violent protest for change in institutions");
        codeAsKey.put("15", "EXHIBIT FORCE POSTURE");
        codeAsKey.put("150", "Demonstrate military or police power");
        codeAsKey.put("152", "Increase military alert status");
        codeAsKey.put("153", "Mobilize or increase police power");
        codeAsKey.put("154", "Mobilize or increase armed forces 155");
        codeAsKey.put("16", "REDUCE RELATIONS");
        codeAsKey.put("160", "Reduce relations");
        codeAsKey.put("161", "Reduce or break diplomatic relations");
        codeAsKey.put("162", "Reduce or stop material aid");
        codeAsKey.put("1621", "Reduce or stop economic assistance 1622");
        codeAsKey.put("163", "Impose embargo");
        codeAsKey.put("165", "Halt mediation");
        codeAsKey.put("166", "Expel or withdraw");
        codeAsKey.put("1661", "Expel or withdraw peacekeepers");
        codeAsKey.put("1662", "Expel or withdraw inspectors");
        codeAsKey.put("17", "COERCE");
        codeAsKey.put("170", "Coerce");
        codeAsKey.put("171", "Seize or damage property");
        codeAsKey.put("1711", "Confiscate property");
        codeAsKey.put("1712", "Destroy property");
        codeAsKey.put("172", "Impose administrative sanctions");
        codeAsKey.put("1721", "Impose restrictions on political freedoms 1722");
        codeAsKey.put("1723", "Impose curfew");
        codeAsKey.put("1724", "Impose state of emergency or martial law");
        codeAsKey.put("173", "Arrest");
        codeAsKey.put("175", "Use tactics of violent repression");
        codeAsKey.put("176", "Attack cybernetically");
        codeAsKey.put("18", "ASSAULT");
        codeAsKey.put("180", "Use unconventional violence");
        codeAsKey.put("182", "Physically assault");
        codeAsKey.put("1821", "Sexually assault");
        codeAsKey.put("1822", "Torture");
        codeAsKey.put("1823", "Kill by physical assault");
        codeAsKey.put("183", "Conduct suicide");
        codeAsKey.put("1832", "Carry out vehicular bombing");
        codeAsKey.put("1833", "Carry out roadside bombing");
        codeAsKey.put("1834", "Carry out location bombing");
        codeAsKey.put("184", "Use as human shield");
        codeAsKey.put("185", "Attempt to assassinate");
        codeAsKey.put("186", "Assassinate");
        codeAsKey.put("19", "FIGHT");
        codeAsKey.put("190", "Use conventional military force");
        codeAsKey.put("192", "Occupy territory");
        codeAsKey.put("193", "Fight with small arms and light weapons");
        codeAsKey.put("194", "Fight with artillery and tanks");
        codeAsKey.put("195", "Employ aerial weapons");
        codeAsKey.put("20", "USE UNCONVENTIONAL MASS VIOLENCE");
        codeAsKey.put("200", "Use unconventional mass violence");
        codeAsKey.put("202", "Engage in mass killings");
        codeAsKey.put("203", "Engage in ethnic cleansing");
        codeAsKey.put("204", "Use weapons of mass destruction");


        valueAsKey= new HashMap<String, String>();
        valueAsKey.put("make public statement", "01");
        valueAsKey.put("make statement", "010");
        valueAsKey.put("make pessimistic comment", "012");
        valueAsKey.put("make optimistic comment", "013");
        valueAsKey.put("consider policy option", "014");
        valueAsKey.put("acknowledge or claim responsibility 016", "015");
        valueAsKey.put("engage in symbolic act", "017");
        valueAsKey.put("make empathetic comment", "018");
        valueAsKey.put("express accord", "019");
        valueAsKey.put("appeal", "02");
        valueAsKey.put("make an appeal or request", "020");
        valueAsKey.put("appeal for material cooperation", "021");
        valueAsKey.put("appeal for economic cooperation 0212", "0211");
        valueAsKey.put("appeal for diplomatic cooperation (such as policy support) 023", "022");
        valueAsKey.put("appeal for economic aid", "0231");
        valueAsKey.put("appeal for military aid", "0232");
        valueAsKey.put("appeal for humanitarian aid", "0233");
        valueAsKey.put("appeal for military protection or peacekeeping", "0234");
        valueAsKey.put("appeal for political reform", "024");
        valueAsKey.put("appeal for policy change", "0242");
        valueAsKey.put("appeal for rights", "0243");
        valueAsKey.put("appeal for change in institutions", "0244");
        valueAsKey.put("appeal for easing of administrative sanctions 0252", "0251");
        valueAsKey.put("appeal for release of persons or property", "0253");
        valueAsKey.put("appeal for easing of economic sanctions", "0254");
        valueAsKey.put("appeal for target to allow international involvement (non-mediation) 0256", "0255");
        valueAsKey.put("appeal to others to meet or negotiate 027", "026");
        valueAsKey.put("appeal to engage in or accept mediation", "028");
        valueAsKey.put("express intent to cooperate", "03");
        valueAsKey.put("express intent to cooperate", "030");
        valueAsKey.put("express intent to engage in material cooperation", "031");
        valueAsKey.put("express intent to cooperate economically", "0311");
        valueAsKey.put("express intent to cooperate militarily", "0312");
        valueAsKey.put("express intent to cooperate on judicial matters 0314", "0313");
        valueAsKey.put("express intent to engage in diplomatic cooperation (such as policy support) 033", "032");
        valueAsKey.put("express intent to provide economic aid", "0331");
        valueAsKey.put("express intent to provide military aid", "0332");
        valueAsKey.put("express intent to provide humanitarian aid", "0333");
        valueAsKey.put("express intent to provide military protection or peacekeeping", "0334");
        valueAsKey.put("express intent to institute political reform", "034");
        valueAsKey.put("express intent to change policy", "0342");
        valueAsKey.put("express intent to provide rights", "0343");
        valueAsKey.put("express intent to change institutions", "0344");
        valueAsKey.put("express intent to ease administrative sanctions", "0351");
        valueAsKey.put("express intent to ease popular dissent", "0352");
        valueAsKey.put("express intent to release persons or property", "0353");
        valueAsKey.put("express intent to ease economic sanctions", "0354");
        valueAsKey.put("express intent to meet or negotiate 037", "036");
        valueAsKey.put("consult", "04");
        valueAsKey.put("consult", "040");
        valueAsKey.put("make a visit", "042");
        valueAsKey.put("host a visit", "043");
        valueAsKey.put("meet at a ”third” location 045", "044");
        valueAsKey.put("engage in negotiation", "046");
        valueAsKey.put("engage in diplomatic cooperation", "05");
        valueAsKey.put("engage in diplomatic cooperation", "050");
        valueAsKey.put("defend verbally", "052");
        valueAsKey.put("rally support on behalf of", "053");
        valueAsKey.put("grant diplomatic recognition 055", "054");
        valueAsKey.put("forgive", "056");
        valueAsKey.put("sign formal agreement", "057");
        valueAsKey.put("engage in material cooperation", "06");
        valueAsKey.put("engage in material cooperation", "060");
        valueAsKey.put("cooperate militarily", "062");
        valueAsKey.put("engage in judicial cooperation", "063");
        valueAsKey.put("share intelligence or information", "064");
        valueAsKey.put("provide aid", "07");
        valueAsKey.put("provide aid", "070");
        valueAsKey.put("provide military aid", "072");
        valueAsKey.put("provide humanitarian aid", "073");
        valueAsKey.put("provide military protection or peacekeeping 075", "074");
        valueAsKey.put("yield", "08");
        valueAsKey.put("yield", "080");
        valueAsKey.put("ease administrative sanctions", "081");
        valueAsKey.put("ease restrictions on political freedoms 0812", "0811");
        valueAsKey.put("ease state of emergency or martial law", "0814");
        valueAsKey.put("ease political dissent", "082");
        valueAsKey.put("accede to requests or demands for political reform", "083");
        valueAsKey.put("accede to demands for change in leadership", "0831");
        valueAsKey.put("accede to demands for change in policy", "0832");
        valueAsKey.put("accede to demands for rights", "0833");
        valueAsKey.put("accede to demands for change in institutions", "0834");
        valueAsKey.put("return", "084");
        valueAsKey.put("ease economic sanctions", "085");
        valueAsKey.put("allow international involvement", "086");
        valueAsKey.put("receive deployment of peacekeepers 0862", "0861");
        valueAsKey.put("allow humanitarian access", "0863");
        valueAsKey.put("de-escalate military engagement 0871", "087");
        valueAsKey.put("ease military blockade", "0872");
        valueAsKey.put("demobilize armed forces", "0873");
        valueAsKey.put("retreat or surrender militarily", "0874");
        valueAsKey.put("investigate", "09");
        valueAsKey.put("investigate", "090");
        valueAsKey.put("investigate war crimes", "094");
        valueAsKey.put("demand", "10");
        valueAsKey.put("demand", "100");
        valueAsKey.put("demand material cooperation", "101");
        valueAsKey.put("demand economic cooperation 1012", "1011");
        valueAsKey.put("demand diplomatic cooperation (such as policy support) 103", "102");
        valueAsKey.put("demand economic aid", "1031");
        valueAsKey.put("demand military aid", "1032");
        valueAsKey.put("demand humanitarian aid", "1033");
        valueAsKey.put("demand military protection or peacekeeping", "1034");
        valueAsKey.put("demand political reform", "104");
        valueAsKey.put("demand policy change", "1042");
        valueAsKey.put("demand rights", "1043");
        valueAsKey.put("demand change in institutions", "1044");
        valueAsKey.put("demand easing of administrative sanctions", "1051");
        valueAsKey.put("demand easing of political dissent", "1052");
        valueAsKey.put("demand release of persons or property", "1053");
        valueAsKey.put("demand easing of economic sanctions", "1054");
        valueAsKey.put("demand that target allows international involvement (non-mediation) 1056", "1055");
        valueAsKey.put("demand meeting", "106");
        valueAsKey.put("disapprove", "11");
        valueAsKey.put("disapprove", "110");
        valueAsKey.put("accuse", "112");
        valueAsKey.put("accuse of crime", "1121");
        valueAsKey.put("accuse of war crimes", "1124");
        valueAsKey.put("accuse of espionage", "1125");
        valueAsKey.put("rally opposition against 114", "113");
        valueAsKey.put("bring lawsuit against", "115");
        valueAsKey.put("find guilty or liable (legally)", "116");
        valueAsKey.put("reject", "12");
        valueAsKey.put("reject", "120");
        valueAsKey.put("reject economic cooperation", "1211");
        valueAsKey.put("reject military cooperation", "1212");
        valueAsKey.put("reject request or demand for material aid", "122");
        valueAsKey.put("reject request for economic aid", "1221");
        valueAsKey.put("reject request for military aid", "1222");
        valueAsKey.put("reject request for humanitarian aid", "1223");
        valueAsKey.put("reject request for military protection or peacekeeping", "1224");
        valueAsKey.put("reject request or demand for political reform", "123");
        valueAsKey.put("reject request for policy change", "1232");
        valueAsKey.put("reject request for rights", "1233");
        valueAsKey.put("reject request for change in institutions", "1234");
        valueAsKey.put("refuse to ease administrative sanctions", "1241");
        valueAsKey.put("refuse to ease popular dissent", "1242");
        valueAsKey.put("refuse to release persons or property", "1243");
        valueAsKey.put("refuse to ease economic sanctions", "1244");
        valueAsKey.put("reject proposal to meet", "125");
        valueAsKey.put("reject plan", "127");
        valueAsKey.put("defy norms", "128");
        valueAsKey.put("veto", "129");
        valueAsKey.put("threaten", "13");
        valueAsKey.put("threaten", "130");
        valueAsKey.put("threaten non-force", "131");
        valueAsKey.put("threaten to reduce or stop aid", "1311");
        valueAsKey.put("threaten with sanctions", "1312");
        valueAsKey.put("threaten to reduce or break relations", "1313");
        valueAsKey.put("threaten with administrative sanctions", "132");
        valueAsKey.put("threaten with restrictions on political freedoms", "1321");
        valueAsKey.put("threaten to ban political parties or politicians", "1322");
        valueAsKey.put("threaten to impose curfew", "1323");
        valueAsKey.put("threaten to impose state of emergency or martial law", "1324");
        valueAsKey.put("threaten with political dissent", "133");
        valueAsKey.put("threaten to halt negotiations", "134");
        valueAsKey.put("threaten to halt mediation", "135");
        valueAsKey.put("threaten to halt international involvement (non-mediation) 137", "136");
        valueAsKey.put("threaten with military force", "138");
        valueAsKey.put("threaten occupation", "1382");
        valueAsKey.put("threaten unconventional violence", "1383");
        valueAsKey.put("threaten conventional attack", "1384");
        valueAsKey.put("threaten attack with wmd 139", "1385");
        valueAsKey.put("protest", "14");
        valueAsKey.put("engage in political dissent", "140");
        valueAsKey.put("demonstrate for leadership change", "1411");
        valueAsKey.put("demonstrate for policy change", "1412");
        valueAsKey.put("demonstrate for rights", "1413");
        valueAsKey.put("demonstrate for change in institutions", "1414");
        valueAsKey.put("conduct hunger strike", "142");
        valueAsKey.put("conduct hunger strike for leadership change", "1421");
        valueAsKey.put("conduct hunger strike for policy change", "1422");
        valueAsKey.put("conduct hunger strike for rights", "1423");
        valueAsKey.put("conduct hunger strike for change in institutions", "1424");
        valueAsKey.put("conduct strike or boycott", "143");
        valueAsKey.put("conduct strike or boycott for leadership change", "1431");
        valueAsKey.put("conduct strike or boycott for policy change", "1432");
        valueAsKey.put("conduct strike or boycott for rights", "1433");
        valueAsKey.put("conduct strike or boycott for change in institutions", "1434");
        valueAsKey.put("obstruct passage", "144");
        valueAsKey.put("obstruct passage to demand leadership change", "1441");
        valueAsKey.put("obstruct passage to demand policy change", "1442");
        valueAsKey.put("obstruct passage to demand rights", "1443");
        valueAsKey.put("obstruct passage to demand change in institutions", "1444");
        valueAsKey.put("protest violently", "145");
        valueAsKey.put("engage in violent protest for leadership change", "1451");
        valueAsKey.put("engage in violent protest for policy change", "1452");
        valueAsKey.put("engage in violent protest for rights", "1453");
        valueAsKey.put("engage in violent protest for change in institutions", "1454");
        valueAsKey.put("exhibit force posture", "15");
        valueAsKey.put("demonstrate military or police power", "150");
        valueAsKey.put("increase military alert status", "152");
        valueAsKey.put("mobilize or increase police power", "153");
        valueAsKey.put("mobilize or increase armed forces 155", "154");
        valueAsKey.put("reduce relations", "16");
        valueAsKey.put("reduce relations", "160");
        valueAsKey.put("reduce or break diplomatic relations", "161");
        valueAsKey.put("reduce or stop material aid", "162");
        valueAsKey.put("reduce or stop economic assistance 1622", "1621");
        valueAsKey.put("impose embargo", "163");
        valueAsKey.put("halt mediation", "165");
        valueAsKey.put("expel or withdraw", "166");
        valueAsKey.put("expel or withdraw peacekeepers", "1661");
        valueAsKey.put("expel or withdraw inspectors", "1662");
        valueAsKey.put("coerce", "17");
        valueAsKey.put("coerce", "170");
        valueAsKey.put("seize or damage property", "171");
        valueAsKey.put("confiscate property", "1711");
        valueAsKey.put("destroy property", "1712");
        valueAsKey.put("impose administrative sanctions", "172");
        valueAsKey.put("impose restrictions on political freedoms 1722", "1721");
        valueAsKey.put("impose curfew", "1723");
        valueAsKey.put("impose state of emergency or martial law", "1724");
        valueAsKey.put("arrest", "173");
        valueAsKey.put("use tactics of violent repression", "175");
        valueAsKey.put("attack cybernetically", "176");
        valueAsKey.put("assault", "18");
        valueAsKey.put("use unconventional violence", "180");
        valueAsKey.put("physically assault", "182");
        valueAsKey.put("sexually assault", "1821");
        valueAsKey.put("torture", "1822");
        valueAsKey.put("kill by physical assault", "1823");
        valueAsKey.put("conduct suicide", "183");
        valueAsKey.put("carry out vehicular bombing", "1832");
        valueAsKey.put("carry out roadside bombing", "1833");
        valueAsKey.put("carry out location bombing", "1834");
        valueAsKey.put("use as human shield", "184");
        valueAsKey.put("attempt to assassinate", "185");
        valueAsKey.put("assassinate", "186");
        valueAsKey.put("fight", "19");
        valueAsKey.put("use conventional military force", "190");
        valueAsKey.put("occupy territory", "192");
        valueAsKey.put("fight with small arms and light weapons", "193");
        valueAsKey.put("fight with artillery and tanks", "194");
        valueAsKey.put("employ aerial weapons", "195");
        valueAsKey.put("use unconventional mass violence", "20");
        valueAsKey.put("use unconventional mass violence", "200");
        valueAsKey.put("engage in mass killings", "202");
        valueAsKey.put("engage in ethnic cleansing", "203");
        valueAsKey.put("use weapons of mass destruction", "204");
    }

    public static void main(String... args) {

        // Example of API
        System.out.println(CAMEO_CODES.getTileFromId("200"));
        System.out.println(CAMEO_CODES.getCode("mass"));

        // This code was used to create the maps
//        String file_location = "ROUTE_TO_FILE/cameo.csv";
//
//        try (BufferedReader br = new BufferedReader(new FileReader(file_location))) {
//            String line;
//            while ((line = br.readLine()) != null) {
//                String[] s = line.split(",");
//
//                System.out.println("valueAsKey.put(\"" + s[1].toLowerCase() + "\", \"" + s[0] + "\");");
//            }
//        } catch (FileNotFoundException e) {
//            e.printStackTrace();
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
    }


}